; Example Configuration for CCTracer
; This file is used to configure the behavior of CCTracer. 
; You can specify which functions to trace, where to output the trace data, and other settings.
enable_tracing = 1
use_perfetto = 0
enable_llvm_log = 0
 
[trace_filters]
; Specify functions to include or exclude from tracing.
; Accept regex to define filter rules
; Use `runtime_<include/exclude>_<files/functions>` to specify filters for runtime functions that you want to emit trace events
; Use `instrument_<include/exclude>_<files/functions>` for functions that you want being instrumented.
; Note that `runtime_*` filters will only affect the events emitted by the tracer itself
; while `instrument_*` filters will affect which functions are instrumented and thus can have a broader impact on the trace data.
; When you change `instrument_*` filters, you need to recompile your program to apply the changes.
; While `runtime_*` filters can be applied at runtime without recompilation, allowing for more dynamic control over the tracing output.
; If you don't specify any filters, all functions will be traced by default.
; The priority of filters is: instrument_exclude > instrument_include > runtime_exclude > runtime_include.
; which means if include and exclude filters conflict, the exclude filter will take precedence, meaning that the function will be excluded from the trace even if it matches an include filter.
; WARNING: when include is specified, only functions that match the include filter will be traced/instrumented, and all others will be ignored.
; For example, if a function matches both `runtime_include_functions` and `runtime_exclude_functions`, it will be excluded from the trace.
; IMPORTANT: Be cautious when using include and exclude filters together, as they can lead to unintended consequences if not configured correctly. Always review your filter settings to ensure they align with your tracing goals.
; instrument_include_functions = main, foo.*
; instrument_exclude_functions = bar.*
; runtime_include_functions = main, foo.*
; runtime_exclude_functions = bar.*
; instrument_include_files = 
; instrument_exclude_files = 
; runtime_include_files = 
; runtime_exclude_files = 


[timeline]
; Configure runtime timeline settings
; Use `trace_begin` to specify a function which the tracer will start emitting events. This is useful to skip initialization phases.
; Use `trace_until` to specify a function which the tracer will stop emitting events. This is useful to skip cleanup phases.
; `trace_begin` and `trace_until` can be used together to define a specific range of execution to trace, or they can be used independently to define open-ended ranges. 
; If neither is specified, tracing will cover the entire execution of the program.
; trace_begin is inclusive, trace_until is exclusive.
trace_begin = main
trace_until = exit
